-- Storage bucket for invoice photos, plus the 2-tap human-confirm flag
-- (PRD 6.3 low-confidence-field flagging) that the initial schema didn't
-- carry a column for.

alter table public.invoice_line_items
  add column confirmed boolean not null default false;

-- Private bucket — objects are only reachable via a signed URL generated by
-- a request that already passes RLS below, never a public URL.
insert into storage.buckets (id, name, public)
values ('invoice-images', 'invoice-images', false)
on conflict (id) do nothing;

-- Path convention: {organization_id}/{invoice_id}/{filename}. The first path
-- segment must match the caller's org id, same tenant-isolation rule as
-- every table in the initial migration.
create policy "invoice_images_tenant_isolation" on storage.objects
  for all
  using (
    bucket_id = 'invoice-images'
    and (storage.foldername(name))[1] = private.current_org_id()
  )
  with check (
    bucket_id = 'invoice-images'
    and (storage.foldername(name))[1] = private.current_org_id()
  );
